### ISSUE TITLE
Stuff

### ISSUE THREAD

**Issue by Steeven9** [MicheleCattaneo/USI_Algo_Bible#1]
See https://github.com/Steeven9/Sorting for additional sorting examples

**Comment by warman69** [comment]
Dear Steeveeen9, thank you very much for your sorting examples.
Would you please be able to help me solve this exercise:

I have to write an algorithm that takes an integer n (let's call it `SUMS-ONE-TWO-THREE(n)`) and, in
time O(n), returns the number of possible ways to write n as a sum of 1, 2, and 3. For
example, `SUMS-ONE-TWO-THREE(4)` shall return 7 because there are 7 ways to write 4 as a
sum of ones, twos, and threes (eg. `1 + 1 + 1 + 1, 1 + 1 + 2`, `1 + 2 + 1`, `2 + 1 + 1`, `2 + 2`, `1 + 3`, `3 + 1`).
Could you also send me an analysis of the complexity of your solution?

Thank you veri much, fellow friend!

**Comment by Steeven9** [comment]
Hi warmanman, this might help you: [https://www.geeksforgeeks.org/count-ofdifferent-ways-express-n-sum-1-3-4/](https://www.geeksforgeeks.org/count-ofdifferent-ways-express-n-sum-1-3-4/), but please don't open unrelated discussions in issues.
